<$PLAN9/src/mkhdr

TARG=plumber plumb

<$PLAN9/src/mkmany

PLUMBER=plumber.go fsys.go match.go rules.go post.go plumber_h.go
PLUMB=plumb.$O

$PLUMB:		$HFILES

$O.plumb:	$PLUMB
$O.plumber:	$PLUMBER
	go build -o $target $PLUMBER

