<$PLAN9/src/mkhdr

TARG=rc
OFILES=\
	code.$O\
	exec.$O\
	getflags.$O\
	glob.$O\
	here.$O\
	io.$O\
	lex.$O\
	parse.$O\
	pcmd.$O\
	pfnc.$O\
	simple.$O\
	subr.$O\
	trap.$O\
	tree.$O\
	var.$O\
	havefork.$O\
	unix.$O\
	y.tab.$O

HFILES=rc.h\
	y.tab.h\
	io.h\
	exec.h\
	fns.h\
	getflags.h\

YFILES=syn.y

CFLAGS=$CFLAGS -DPlan9

<$PLAN9/src/mkone
